In [23]:
import pandas as pd
import re
import openpyxl

In [24]:
emails_df = pd.read_csv('../data/02_cleaned_emails_unlabelled_internal.csv')
emails_df.head(5)

,Date,From,To,Subject,X_From,X_To,Message
0,"Fri, 4 May 2001 13:51:00 -0700 (PDT)",phillip.allen@enron.com,john.lavorato@enron.com,Re:,Phillip K Allen,John J Lavorato <John J Lavorato/ENRON@enronXg...,Traveling to have a business meeting takes the...
1,"Mon, 23 Oct 2000 06:13:00 -0700 (PDT)",phillip.allen@enron.com,randall.gay@enron.com,No Subject,Phillip K Allen,Randall L Gay,"Randy,\n Can you send me a schedule of the sal..."
2,"Tue, 22 Aug 2000 07:44:00 -0700 (PDT)",phillip.allen@enron.com,"david.l.johnson@enron.com, john.shafer@enron.com",No Subject,Phillip K Allen,"david.l.johnson@enron.com, John Shafer",Please cc the following distribution list with...
3,"Mon, 16 Oct 2000 06:42:00 -0700 (PDT)",phillip.allen@enron.com,buck.buckner@honeywell.com,Re: FW: fixed forward or other Collar floor ga...,Phillip K Allen,"""Buckner, Buck"" <buck.buckner@honeywell.com> @...","Mr. Buckner,\n For delivered gas behind San Di..."
4,"Fri, 13 Oct 2000 06:45:00 -0700 (PDT)",phillip.allen@enron.com,stagecoachmama@hotmail.com,No Subject,Phillip K Allen,stagecoachmama@hotmail.com,"Lucy,\n Here are the rentrolls:\n Open them an..."

In [25]:
emails_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72012 entries, 0 to 72011
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Date     72012 non-null  object
 1   From     72012 non-null  object
 2   To       72012 non-null  object
 3   Subject  72012 non-null  object
 4   X_From   72012 non-null  object
 5   X_To     72012 non-null  object
 6   Message  72012 non-null  object
dtypes: object(7)
memory usage: 3.8+ MB

In [26]:
emails_df.describe(include='object').T

         count unique                                                top  freq
Date     72012  67840              Mon, 31 Dec 1979 16:00:00 -0800 (PST)   121
From     72012   5054                            jeff.dasovich@enron.com  1926
To       72012  26737                               tana.jones@enron.com   930
Subject  72012  53055                                         No Subject  2443
X_From   72012   7392                                           Kay Mann  1690
X_To     72012  31048                                         Tana Jones   826
Message  72012  72012  Traveling to have a business meeting takes the...     1

In [27]:
emails_df['DISC'] = ""
emails_df

,Date,From,To,Subject,X_From,X_To,Message,DISC
0,"Fri, 4 May 2001 13:51:00 -0700 (PDT)",phillip.allen@enron.com,john.lavorato@enron.com,Re:,Phillip K Allen,John J Lavorato <John J Lavorato/ENRON@enronXg...,Traveling to have a business meeting takes the...,
1,"Mon, 23 Oct 2000 06:13:00 -0700 (PDT)",phillip.allen@enron.com,randall.gay@enron.com,No Subject,Phillip K Allen,Randall L Gay,"Randy,\n Can you send me a schedule of the sal...",
2,"Tue, 22 Aug 2000 07:44:00 -0700 (PDT)",phillip.allen@enron.com,"david.l.johnson@enron.com, john.shafer@enron.com",No Subject,Phillip K Allen,"david.l.johnson@enron.com, John Shafer",Please cc the following distribution list with...,
3,"Mon, 16 Oct 2000 06:42:00 -0700 (PDT)",phillip.allen@enron.com,buck.buckner@honeywell.com,Re: FW: fixed forward or other Collar floor ga...,Phillip K Allen,"""Buckner, Buck"" <buck.buckner@honeywell.com> @...","Mr. Buckner,\n For delivered gas behind San Di...",
4,"Fri, 13 Oct 2000 06:45:00 -0700 (PDT)",phillip.allen@enron.com,stagecoachmama@hotmail.com,No Subject,Phillip K Allen,stagecoachmama@hotmail.com,"Lucy,\n Here are the rentrolls:\n Open them an...",
...,...,...,...,...,...,...,...,...
72007,"Wed, 9 Jan 2002 07:30:16 -0800 (PST)",john.zufferli@enron.com,carol.moline@powerpool.ab.ca,Chevron Contract,"Zufferli, John </O=ENRON/OU=NA/CN=RECIPIENTS/C...",'carol.moline@powerpool.ab.ca',Enron Canada Power Corp acknowledges the chang...,
72008,"Wed, 2 Jan 2002 09:55:40 -0800 (PST)",john.zufferli@enron.com,frank.senders@pandora.be,Training,"Zufferli, John </O=ENRON/OU=NA/CN=RECIPIENTS/C...",'frank.senders@pandora.be',I am interested in a program for myself. I am...,
72009,"Thu, 20 Dec 2001 09:51:58 -0800 (PST)",john.zufferli@enron.com,stephanie.sever@enron.com,Gas and Power EOL Access,"Zufferli, John </O=ENRON/OU=NA/CN=RECIPIENTS/C...","Sever, Stephanie </O=ENRON/OU=NA/CN=RECIPIENTS...",Here is the update list that you requested. Mi...,
72010,"Wed, 12 Dec 2001 09:14:32 -0800 (PST)",john.zufferli@enron.com,astrid.montes@powerpool.ab.ca,Digital Certificate for TAU,"Zufferli, John </O=ENRON/OU=NA/CN=RECIPIENTS/C...",'astrid.montes@powerpool.ab.ca',Please set up access for the digital certifica...,
72011,"Wed, 28 Nov 2001 13:30:11 -0800 (PST)",john.zufferli@enron.com,kori.loibl@enron.com,Trade with John Lavorato,"Zufferli, John </O=ENRON/OU=NA/CN=RECIPIENTS/C...","Loibl, Kori </O=ENRON/OU=NA/CN=RECIPIENTS/CN=K...",This is a trade with OIL-SPEC-HEDGE-NG (John L...,

In [29]:
emails_df_trimmed = emails_df.drop(columns=['X_To', 'X_From'])
emails_df_trimmed.to_excel('../data/03_emails_unlabelled.xlsx', index=False)

IllegalCharacterError: Premonition?




 British Trader Sentenced to Prison
this could be you
British Trader Sentenced to Prison
                  By Jill Lawless
                  Associated Press Writer
                  Tuesday, Oct. 3, 2000; 2:07 p.m. EDT
                  LONDON )) A futures trader who bet the wrong way on U.S.
                  unemployment figures, and destroyed a company in 92
minutes, was
                  sentenced Tuesday to more than three years in jail.
                  "The position got worse and he was just numb," a defense
attorney said,
                  comparing the debacle to a bad night at a roulette wheel.
                  Stephen Humphries, 25, formerly a trader at Sussex Futures
Ltd., sank
                  the company with losses of $1.1 million.
                  "During that afternoon of Friday, Aug. 6, 1999, during a
period of one
                  hour, 32 minutes, the company's hard-earned reputation and
value was
                  destroyed at a stroke ... by the fraudulent trading
activity of one man,
                  Stephen Humphries," said prosecution lawyer Martin Hicks.
                  Humphries pleaded guilty to one count of fraudulent
trading. Judge Denis
                  Levy sentenced him to three years and nine months in
prison.
                  Southwark Crown Court heard testimony that Humphries ran up
the
                  losses by trading futures contracts in government bonds,
and repeatedly
                  lied to superiors about his trades.
                  When worried colleagues left to summon the firm's senior
broker,
                  Humphries fled the building.
                  After the huge one-day loss, the company's creditor banks
balked and a
                  financial regulator was called in. Sussex Futures ) which
employed 70
                  brokers ) ceased trading three months later with losses of
$3.4 million.
                  The court was told that Humphries' trading losses began on
the morning of
                  Aug. 6, wiping out two-thirds of his $25,000 trading
deposit by lunchtime.
                  The situation worsened at 1:30 p.m., when U.S. economic
figures were
                  released showing no increase in the unemployment rate. The
data made
                  U.S. interest rates more likely to rise and reduced the
value of
                  fixed-interest investments such as British government
bonds.
                  Nonetheless, Humphries continued to buy, in quantities that
exceeded his
                  trading ceiling. Questioned by co-workers about the large
trades going
                  through his account, Humphries said he was in the process
of selling out.
                  By the time he fled, he held more than 100 times his
trading limit in futures.
                  "In the course of an afternoon ... you ruined not only your
own career, but
                  the career of many others and you caused a prosperous
company, Sussex
                  Futures Limited, to go into liquidation, causing loss to
the company which
                  trusted you and employed you," said the judge.
                  Defense lawyer Simon Ward said Humphries had been under
intense
                  financial pressure and was "deeply sorry."
                  He had lost a previous job when a trading company he worked
for went
                  under ) also at the hands of a rogue trader.
                  He had taken out large bank loans, amassed a substantial
credit-card debt
                  and had borrowed from his father's life savings. He and his
partner, with
                  whom he had two children, had a third baby die, a blow that
affected
                  Humphries' judgment, Ward said.
                  "This is a tragic and very upsetting case," said Ward. "He
was 24, under
                  intense financial and personal pressure and, in effect,
lost his head at the
                  roulette table."
                               , Copyright 2000 The Associated Press
                                        Back to the top cannot be used in worksheets.